from __future__ import annotations

from scripts.models import FieldExpectation, Scenario


PROBLEM_DETAIL_FIELDS = (
    "type",
    "title",
    "status",
    "detail",
    "instance",
    "errorCode",
    "correlationId",
)


def expect(path: str, value: object) -> FieldExpectation:
    return FieldExpectation(path, value)


def problem(
    scenario_id: str,
    use_case: str,
    actor: str,
    intent: str,
    resource: str,
    method: str,
    path: str,
    status: int,
    error_code: str,
    body: object = None,
) -> Scenario:
    return Scenario(
        id=scenario_id,
        use_case=use_case,
        actor=actor,
        intent=intent,
        resource=resource,
        method=method,
        path=path,
        expected_status=status,
        body=body,
        required_paths=PROBLEM_DETAIL_FIELDS,
        expected_values=(
            expect("status", status),
            expect("errorCode", error_code),
            expect("instance", path.split("?", 1)[0]),
        ),
        compare_paths=("type", "title", "status", "errorCode", "instance"),
    )


SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        id="service-health",
        use_case="Service liveness",
        actor="System",
        intent="Confirm service process is running",
        resource="health",
        method="GET",
        path="/health",
        expected_status=200,
        required_paths=("status", "service"),
        expected_values=(expect("status", "UP"), expect("service", "partner-source")),
        compare_paths=("status", "service"),
    ),
    Scenario(
        id="service-readiness",
        use_case="Service readiness",
        actor="System",
        intent="Confirm seed data and in-memory persistence are ready",
        resource="ready",
        method="GET",
        path="/ready",
        expected_status=200,
        required_paths=("status", "service", "checks.persistence", "checks.seedData"),
        expected_values=(
            expect("status", "READY"),
            expect("service", "partner-source"),
            expect("checks.persistence", "UP"),
            expect("checks.seedData", "UP"),
        ),
        compare_paths=("status", "service", "checks.persistence", "checks.seedData"),
    ),
    Scenario(
        id="CSA-02-order-status-happy-path",
        use_case="CSA-02",
        actor="Customer Service Agent",
        intent="View current order status",
        resource="orders",
        method="GET",
        path="/api/v1/orders/ORD-1001/status",
        expected_status=200,
        required_paths=(
            "orderId",
            "currentStatus",
            "statusLabel",
            "deliveryWindow",
            "assignedDriver.driverId",
            "lastUpdatedAt",
        ),
        expected_values=(
            expect("orderId", "ORD-1001"),
            expect("currentStatus", "OUT_FOR_DELIVERY"),
            expect("statusLabel", "Out for delivery"),
            expect("assignedDriver.driverId", "DRV-2001"),
        ),
        compare_paths=("orderId", "currentStatus", "statusLabel", "assignedDriver.driverId"),
    ),
    Scenario(
        id="CSA-03-order-timeline-happy-path",
        use_case="CSA-03",
        actor="Customer Service Agent",
        intent="View chronological order timeline",
        resource="status-events",
        method="GET",
        path="/api/v1/orders/ORD-1001/timeline?page=1&pageSize=20",
        expected_status=200,
        required_paths=("orderId", "items", "page", "pageSize", "totalItems"),
        expected_values=(
            expect("orderId", "ORD-1001"),
            expect("page", 1),
            expect("pageSize", 20),
            expect("totalItems", 5),
            expect("items[0].eventId", "EVT-4001"),
            expect("items[4].eventId", "EVT-4005"),
        ),
        compare_paths=("orderId", "page", "pageSize", "totalItems", "items[0].status", "items[4].status"),
    ),
    Scenario(
        id="DA-01-driver-profile-happy-path",
        use_case="DA-01",
        actor="Delivery Agent",
        intent="Confirm seeded driver identity",
        resource="drivers",
        method="GET",
        path="/api/v1/drivers/DRV-2001",
        expected_status=200,
        required_paths=("driverId", "displayName", "availabilityStatus", "activeAssignmentCount"),
        expected_values=(
            expect("driverId", "DRV-2001"),
            expect("availabilityStatus", "AVAILABLE"),
            expect("activeAssignmentCount", 2),
        ),
        compare_paths=("driverId", "displayName", "availabilityStatus", "activeAssignmentCount"),
    ),
    Scenario(
        id="DA-02-driver-assignments-active-driver",
        use_case="DA-02",
        actor="Delivery Agent",
        intent="Retrieve active assigned orders",
        resource="assignments",
        method="GET",
        path="/api/v1/drivers/DRV-2001/assignments?page=1&pageSize=20",
        expected_status=200,
        required_paths=("driverId", "items", "page", "pageSize", "totalItems"),
        expected_values=(
            expect("driverId", "DRV-2001"),
            expect("page", 1),
            expect("pageSize", 20),
            expect("totalItems", 2),
        ),
        contains_values=(expect("items[*].orderId", ("ORD-1001", "ORD-1002")),),
        compare_paths=("driverId", "page", "pageSize", "totalItems"),
    ),
    Scenario(
        id="DA-02-driver-assignments-filtered-status",
        use_case="DA-02",
        actor="Delivery Agent",
        intent="Filter assigned orders by current status",
        resource="assignments",
        method="GET",
        path="/api/v1/drivers/DRV-2001/assignments?status=OUT_FOR_DELIVERY&page=1&pageSize=20",
        expected_status=200,
        required_paths=("driverId", "items", "page", "pageSize", "totalItems"),
        expected_values=(
            expect("driverId", "DRV-2001"),
            expect("page", 1),
            expect("pageSize", 20),
            expect("totalItems", 1),
        ),
        contains_values=(expect("items[*].orderId", ("ORD-1001",)),),
        all_values=(expect("items[*].currentStatus", "OUT_FOR_DELIVERY"),),
        compare_paths=("driverId", "page", "pageSize", "totalItems"),
    ),
    Scenario(
        id="DA-02-driver-assignments-empty-driver",
        use_case="DA-02",
        actor="Delivery Agent",
        intent="Retrieve assignments for driver with no active assignments",
        resource="assignments",
        method="GET",
        path="/api/v1/drivers/DRV-2003/assignments?page=1&pageSize=20",
        expected_status=200,
        required_paths=("driverId", "items", "page", "pageSize", "totalItems"),
        expected_values=(
            expect("driverId", "DRV-2003"),
            expect("items", []),
            expect("totalItems", 0),
        ),
        compare_paths=("driverId", "items", "totalItems"),
    ),
    problem(
        "CSA-01-order-status-missing-order",
        "CSA-01",
        "Customer Service Agent",
        "Look up missing order by order ID",
        "orders",
        "GET",
        "/api/v1/orders/ORD-9999/status",
        404,
        "ORDER_NOT_FOUND",
    ),
    problem(
        "CSA-01-order-status-invalid-id",
        "CSA-01",
        "Customer Service Agent",
        "Reject malformed order ID",
        "orders",
        "GET",
        "/api/v1/orders/INVALID/status",
        400,
        "INVALID_REQUEST",
    ),
    problem(
        "CSA-03-order-timeline-missing-order",
        "CSA-03",
        "Customer Service Agent",
        "Reject timeline lookup for missing order",
        "status-events",
        "GET",
        "/api/v1/orders/ORD-9999/timeline?page=1&pageSize=20",
        404,
        "ORDER_NOT_FOUND",
    ),
    problem(
        "CSA-03-order-timeline-invalid-page",
        "CSA-03",
        "Customer Service Agent",
        "Reject invalid timeline pagination",
        "status-events",
        "GET",
        "/api/v1/orders/ORD-1001/timeline?page=0&pageSize=20",
        400,
        "INVALID_REQUEST",
    ),
    problem(
        "DA-01-driver-profile-missing-driver",
        "DA-01",
        "Delivery Agent",
        "Reject missing driver lookup",
        "drivers",
        "GET",
        "/api/v1/drivers/DRV-9999",
        404,
        "DRIVER_NOT_FOUND",
    ),
    problem(
        "DA-01-driver-profile-invalid-id",
        "DA-01",
        "Delivery Agent",
        "Reject malformed driver ID",
        "drivers",
        "GET",
        "/api/v1/drivers/INVALID",
        400,
        "INVALID_REQUEST",
    ),
    problem(
        "DA-02-driver-assignments-invalid-status-filter",
        "DA-02",
        "Delivery Agent",
        "Reject invalid assignment status filter",
        "assignments",
        "GET",
        "/api/v1/drivers/DRV-2001/assignments?status=NOT_A_STATUS&page=1&pageSize=20",
        400,
        "INVALID_REQUEST",
    ),
    problem(
        "DA-02-driver-assignments-missing-driver",
        "DA-02",
        "Delivery Agent",
        "Reject assignment lookup for missing driver",
        "assignments",
        "GET",
        "/api/v1/drivers/DRV-9999/assignments?page=1&pageSize=20",
        404,
        "DRIVER_NOT_FOUND",
    ),
    problem(
        "DA-02-driver-assignments-invalid-page",
        "DA-02",
        "Delivery Agent",
        "Reject invalid assignment pagination",
        "assignments",
        "GET",
        "/api/v1/drivers/DRV-2001/assignments?page=0&pageSize=20",
        400,
        "INVALID_REQUEST",
    ),
    problem(
        "DA-05-status-event-unassigned-driver",
        "DA-05",
        "Delivery Agent",
        "Reject status event from unassigned driver",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-1001/status-events",
        403,
        "ORDER_NOT_ASSIGNED_TO_DRIVER",
        body={
            "driverId": "DRV-2002",
            "status": "DELIVERED",
            "occurredAt": "2026-06-30T15:40:00+08:00",
            "note": "This should fail because DRV-2002 is not assigned to ORD-1001",
            "proofOfDeliveryAvailable": False,
        },
    ),
    problem(
        "DA-05-status-event-missing-driver",
        "DA-05",
        "Delivery Agent",
        "Reject status event from missing driver",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-1001/status-events",
        404,
        "DRIVER_NOT_FOUND",
        body={
            "driverId": "DRV-9999",
            "status": "DELIVERED",
            "occurredAt": "2026-06-30T15:41:00+08:00",
            "note": "This should fail because DRV-9999 does not exist",
            "proofOfDeliveryAvailable": False,
        },
    ),
    problem(
        "DA-05-status-event-invalid-transition",
        "DA-05",
        "Delivery Agent",
        "Reject invalid status transition",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-1003/status-events",
        409,
        "INVALID_STATUS_TRANSITION",
        body={
            "driverId": "DRV-2001",
            "status": "OUT_FOR_DELIVERY",
            "occurredAt": "2026-06-30T15:42:00+08:00",
            "note": "This should fail because ORD-1003 is already delivered",
            "proofOfDeliveryAvailable": False,
        },
    ),
    problem(
        "DA-05-status-event-future-occurred-at",
        "DA-05",
        "Delivery Agent",
        "Reject semantically invalid future status event",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-1001/status-events",
        422,
        "INVALID_STATUS_EVENT",
        body={
            "driverId": "DRV-2001",
            "status": "DELIVERED",
            "occurredAt": "2099-06-30T15:42:30+08:00",
            "note": "This should fail because the event shape is valid but the event time is semantically invalid",
            "proofOfDeliveryAvailable": False,
        },
    ),
    problem(
        "DA-05-status-event-missing-order",
        "DA-05",
        "Delivery Agent",
        "Reject status event for missing order",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-9999/status-events",
        404,
        "ORDER_NOT_FOUND",
        body={
            "driverId": "DRV-2001",
            "status": "DELIVERED",
            "occurredAt": "2026-06-30T15:43:00+08:00",
            "note": "This should fail because the order does not exist",
            "proofOfDeliveryAvailable": False,
        },
    ),
    problem(
        "DA-05-status-event-malformed-body",
        "DA-05",
        "Delivery Agent",
        "Reject malformed status event body",
        "status-events",
        "POST",
        "/api/v1/orders/ORD-1001/status-events",
        400,
        "INVALID_REQUEST",
        body={
            "driverId": "DRV-2001",
            "status": "DELIVERED",
            "occurredAt": "not-a-date",
            "unexpectedField": True,
        },
    ),
    Scenario(
        id="DA-06-status-event-delivered-happy-path",
        use_case="DA-06",
        actor="Delivery Agent",
        intent="Mark order as delivered",
        resource="status-events",
        method="POST",
        path="/api/v1/orders/ORD-1001/status-events",
        expected_status=201,
        body={
            "driverId": "DRV-2001",
            "status": "DELIVERED",
            "occurredAt": "2026-06-30T15:45:00+08:00",
            "location": {
                "label": "Customer address",
                "latitude": 1.3521,
                "longitude": 103.9448,
                "capturedAt": "2026-06-30T15:45:00+08:00",
            },
            "note": "Left with reception",
            "proofOfDeliveryAvailable": True,
        },
        required_paths=(
            "eventId",
            "orderId",
            "previousStatus",
            "newStatus",
            "statusLabel",
            "occurredAt",
            "actorType",
            "actorId",
            "orderCurrentStatus",
        ),
        expected_values=(
            expect("orderId", "ORD-1001"),
            expect("previousStatus", "OUT_FOR_DELIVERY"),
            expect("newStatus", "DELIVERED"),
            expect("statusLabel", "Delivered"),
            expect("actorType", "DRIVER"),
            expect("actorId", "DRV-2001"),
            expect("orderCurrentStatus", "DELIVERED"),
        ),
        compare_paths=("orderId", "previousStatus", "newStatus", "statusLabel", "actorType", "actorId", "orderCurrentStatus"),
        state_changing=True,
    ),
)
