package com.waypoint.partnersource.shared.error;

public enum ErrorCode {
    INVALID_REQUEST,
    UNAUTHENTICATED,
    ACCESS_DENIED,
    ORDER_NOT_FOUND,
    DRIVER_NOT_FOUND,
    ASSIGNMENT_NOT_FOUND,
    ORDER_NOT_ASSIGNED_TO_DRIVER,
    INVALID_STATUS_TRANSITION,
    INVALID_STATUS_EVENT,
    INTERNAL_SERVER_ERROR
}
